function run_parity(input_file, output_file)
%RUN_PARITY Evaluate the original MATLAB implementation on a shared fixture.

script_dir = fileparts(mfilename('fullpath'));
repo_root = fileparts(fileparts(script_dir));
addpath(fullfile(repo_root, 'AXYB_prob_solver'));
addpath(fullfile(repo_root, 'LieGroup'));
addpath(fullfile(repo_root, 'synthetic_data_generation'));

data = load(input_file);
A = data.A;
B = data.B;
C = data.C;
X0 = data.X0;
Y0 = data.Y0;
invSig_wN = data.invSig_wN;
invSig_pN = data.invSig_pN;
invSig_wM = data.invSig_wM;
invSig_pM = data.invSig_pM;

J_conf1 = computeLogL(X0, Y0, A, B, C, invSig_wN, invSig_pN, invSig_wM, invSig_pM, 1);
[GwX_conf1, GwY_conf1, GwC_conf1, GqX_conf1, GqY_conf1, GqC_conf1, J_grad_conf1] = ...
    gradLogL(X0, Y0, num2cell(A,[1,2]), num2cell(B,[1,2]), num2cell(C,[1,2]), ...
    num2cell(invSig_wN,[1,2]), num2cell(invSig_pN,[1,2]), ...
    num2cell(invSig_wM,[1,2]), num2cell(invSig_pM,[1,2]), 1);

J_conf2 = computeLogL(X0, Y0, A, B, C, invSig_wN, invSig_pN, invSig_wM, invSig_pM, 2);
[GwX_conf2, GwY_conf2, GwC_conf2, GqX_conf2, GqY_conf2, GqC_conf2, J_grad_conf2] = ...
    gradLogL(X0, Y0, num2cell(A,[1,2]), num2cell(B,[1,2]), num2cell(C,[1,2]), ...
    num2cell(invSig_wN,[1,2]), num2cell(invSig_pN,[1,2]), ...
    num2cell(invSig_wM,[1,2]), num2cell(invSig_pM,[1,2]), 2);

J_conf3 = computeLogL_noiselessA(X0, Y0, A, B, invSig_wM, invSig_pM);
[GwX_conf3, GwY_conf3, GqX_conf3, GqY_conf3, J_grad_conf3] = ...
    gradLogL_noiselessA(X0, Y0, num2cell(A,[1,2]), num2cell(B,[1,2]), ...
    num2cell(invSig_wM,[1,2]), num2cell(invSig_pM,[1,2]));

[covX_conf1, covY_conf1, Z_conf1] = computeUncertainty( ...
    X0, Y0, C, invSig_wN, invSig_pN, invSig_wM, invSig_pM, 1);
[covX_conf2, covY_conf2, Z_conf2] = computeUncertainty( ...
    X0, Y0, C, invSig_wN, invSig_pN, invSig_wM, invSig_pM, 2);
[covX_conf3, covY_conf3, Z_conf3] = computeUncertainty_noiseConf3( ...
    X0, Y0, B, invSig_wM, invSig_pM);

step_R = data.step_R;
step_p = data.step_p;
solver_precision = repmat(eye(3), [1, 1, size(A,3)]);
[X_solver_conf1, Y_solver_conf1, C_solver_conf1, J_solver_conf1] = solveAXYB_prob( ...
    A, B, X0, Y0, solver_precision, solver_precision, solver_precision, solver_precision, 1, step_R, step_p);
[X_solver_conf2, Y_solver_conf2, C_solver_conf2, J_solver_conf2] = solveAXYB_prob( ...
    A, B, X0, Y0, solver_precision, solver_precision, solver_precision, solver_precision, 2, step_R, step_p);
[X_solver_conf3, Y_solver_conf3, J_solver_conf3] = solveAXYB_prob_noiselessA( ...
    A, B, X0, Y0, solver_precision, solver_precision, step_R, step_p);

save(output_file, ...
    'J_conf1', 'GwX_conf1', 'GwY_conf1', 'GwC_conf1', 'GqX_conf1', 'GqY_conf1', 'GqC_conf1', 'J_grad_conf1', ...
    'J_conf2', 'GwX_conf2', 'GwY_conf2', 'GwC_conf2', 'GqX_conf2', 'GqY_conf2', 'GqC_conf2', 'J_grad_conf2', ...
    'J_conf3', 'GwX_conf3', 'GwY_conf3', 'GqX_conf3', 'GqY_conf3', 'J_grad_conf3', ...
    'covX_conf1', 'covY_conf1', 'Z_conf1', 'covX_conf2', 'covY_conf2', 'Z_conf2', ...
    'covX_conf3', 'covY_conf3', 'Z_conf3', ...
    'X_solver_conf1', 'Y_solver_conf1', 'C_solver_conf1', 'J_solver_conf1', ...
    'X_solver_conf2', 'Y_solver_conf2', 'C_solver_conf2', 'J_solver_conf2', ...
    'X_solver_conf3', 'Y_solver_conf3', 'J_solver_conf3', '-v7');
end
